### ISSUE TITLE
Don't show author of project owner

### ISSUE THREAD

**Issue by timmo001** [ludeeus/reporeleaser#1]
**Is your feature request related to a problem? Please describe.**

The author should/could only be shown if the author is not the owner of the repo 

**Describe the solution you'd like**

Remove attribution for project / repo owners.

**Describe alternatives you've considered**

An extra parameter perhaps?

**Additional context**

See below for example of @ludeeus thanking @ludeeus :smile: 

![image](https://user-images.githubusercontent.com/28114703/52297758-5bd55500-2979-11e9-901f-dd035eece457.png)

**Comment by ludeeus** [comment]
:(

**Comment by ludeeus** [comment]
<https://github.com/ludeeus/reporeleaser/commit/ca5befe9517f4e4ca260d0ad158e55a9e7787562>
It worked, I just forgot to run the updated code when testing :P

**Comment by timmo001** [comment]
Thanks! :+1:  :1st_place_medal:
